### ISSUE TITLE
populse_mia crash with the very last capsul version (install from source)

### ISSUE THREAD

**Issue by servoz** [populse/capsul#135]
This is not the case with the [CheeseShop version](https://pypi.org/project/capsul/) (observed only after an installation from source).

This may not be view as real issue, since we are considering delegating the configuration of pipelines, currently managed in mia, to the capsul engine. But before this future change in mia, please don't update the CheeseShop with the fresh version of capsul currently in github!

Indeed, the problem seems to come from the new configuration management in capsul (and which seems already wants to take control of mia's configuration!!!! :-):

```
Traceback (most recent call last):
  File "/home/econdami/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1458, in run
    use_matlab=True, output_directory=spm_path)
  File "/home/econdami/.local/lib/python3.6/site-packages/capsul-2.2.1-py3.6.egg/capsul/study_config/study_config.py", line 239, in __init__
    self.initialize_modules()
  File "/home/econdami/.local/lib/python3.6/site-packages/capsul-2.2.1-py3.6.egg/capsul/study_config/study_config.py", line 268, in initialize_modules
    module.initialize_module()
  File "/home/econdami/.local/lib/python3.6/site-packages/capsul-2.2.1-py3.6.egg/capsul/study_config/config_modules/matlab_config.py", line 69, in initialize_module
    raise EnvironmentError('matlab_exec must be defined in order '

```

**Comment by denisri** [comment]
Indeed there was a problem in the StudyConfig/CapsulEngine synchronization for the matlab module. It should be fixed now.

**Comment by servoz** [comment]
Thanks @denisri, it works very well now! I close the ticket.

**Comment by servoz** [comment]
I spent few hours today trying to understand why I observe the same thing on a Mac... by going back to the pypi capsul version, it works well (like before your fix !). The most surprising thing is that there is no problem with my station (linux), since your fix .... I can't believe this is due to an OS problem..... Maybe you'll have an idea????

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/populse_mia-1.2.1-py3.7.egg/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1462, in run
    output_directory=spm_standalone_path, spm_standalone=True)
  File "/usr/local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/study_config/study_config.py", line 239, in __init__
    self.initialize_modules()
  File "/usr/local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/study_config/study_config.py", line 268, in initialize_modules
    module.initialize_module()
  File "/usr/local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/study_config/config_modules/spm_config.py", line 67, in initialize_module
    check_spm_configuration(self.study_config)
  File "/usr/local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/subprocess/spm.py", line 92, in check_spm_configuration
    spm_engine.check_spm_configuration(study_config.engine)
  File "/usr/local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/engine/module/spm.py", line 55, in check_spm_configuration
    raise EnvironmentError(error_message)
OSError: SPM version is not defined (maybe /Users/invites/spm12 is not a valid SPM directory)
