### ISSUE TITLE
populse_mia's unit tests do not seem to work with the latest version (github) of capsul

### ISSUE THREAD

**Issue by servoz** [populse/capsul#162]
With the pypi version, except for a few warnings, [the tests are going well](https://travis-ci.org/github/populse/populse_mia/jobs/677359805).
With the current github version, the tests fail:
```
$ python3 test.py -v
test_add_path (__main__.TestMIADataBrowser) ... ok
test_add_tag (__main__.TestMIADataBrowser) ... ok
test_advanced_search (__main__.TestMIADataBrowser) ... ok
test_brick_history (__main__.TestMIADataBrowser) ... ok
test_clear_cell (__main__.TestMIADataBrowser) ... ok
test_clone_tag (__main__.TestMIADataBrowser) ... ok
test_count_table (__main__.TestMIADataBrowser) ... ok
test_mia_preferences (__main__.TestMIADataBrowser) ... ok
test_modify_table (__main__.TestMIADataBrowser) ... ok
test_multiple_sort (__main__.TestMIADataBrowser) ... ok
test_open_project (__main__.TestMIADataBrowser) ... ok
test_open_project_filter (__main__.TestMIADataBrowser) ... ok
test_project_properties (__main__.TestMIADataBrowser) ... ok
test_projects_removed_from_current_projects (__main__.TestMIADataBrowser) ... ok
test_rapid_search (__main__.TestMIADataBrowser) ... ok
test_remove_scan (__main__.TestMIADataBrowser) ... ok
test_remove_tag (__main__.TestMIADataBrowser) ... ok
test_reset_cell (__main__.TestMIADataBrowser) ... ok
test_reset_column (__main__.TestMIADataBrowser) ... ok
test_reset_row (__main__.TestMIADataBrowser) ... ok
test_save_project (__main__.TestMIADataBrowser) ... ok
test_send_documents_to_pipeline (__main__.TestMIADataBrowser) ... ok
test_set_value (__main__.TestMIADataBrowser) ... ok
test_sort (__main__.TestMIADataBrowser) ... ok
test_tab_change (__main__.TestMIADataBrowser) ... ok
test_undo_redo_databrowser (__main__.TestMIADataBrowser) ... ok
test_unnamed_project_software_opening (__main__.TestMIADataBrowser) ... ok
test_utils (__main__.TestMIADataBrowser) ... ok
test_visualized_tags (__main__.TestMIADataBrowser) ... ok
test_add_tab (__main__.TestMIAPipelineManager) ... ok
test_close_tab (__main__.TestMIAPipelineManager) ... ok
Exception ignored in: <function PipelineDevelopperView.__del__ at 0x7f1ebc624560>
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 2545, in __del__
    self.release_pipeline()
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 2622, in release_pipeline
    self.scene = PipelineScene(self)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 1434, in __init__
    super(PipelineScene, self).__init__(parent)
RuntimeError: wrapped C/C++ object of type PipelineEditor has been deleted
Exception ignored in: <function PipelineScene.__del__ at 0x7f1ebc679320>
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 1458, in __del__
    if hasattr(self, 'pos'):
RuntimeError: super-class __init__() of type PipelineScene was never called
Exception ignored in: <function PipelineDevelopperView.__del__ at 0x7f1ebc624560>
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 2545, in __del__
    self.release_pipeline()
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 2622, in release_pipeline
    self.scene = PipelineScene(self)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 1434, in __init__
    super(PipelineScene, self).__init__(parent)
RuntimeError: wrapped C/C++ object of type PipelineEditor has been deleted
Exception ignored in: <function PipelineScene.__del__ at 0x7f1ebc679320>
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 1458, in __del__
    if hasattr(self, 'pos'):
RuntimeError: super-class __init__() of type PipelineScene was never called
test_delete_processes (__main__.TestMIAPipelineManager) ... /home/econdami/.local/lib/python3.7/site-packages/soma_base-4.6.5-py3.7.egg/soma/utils/functiontools.py:135: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  return inspect.getargspec(callable)
ok
test_display_filter (__main__.TestMIAPipelineManager) ... EXCEPTION: expected str, bytes or os.PathLike object, not _Undefined
while syncing nipype parameter synchronize on Threshold
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <capsul.process.process.NipypeProcess object at 0x7f1e7272b890>, trait: synchronize, old value: 0, new value: 2
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/nipype_process.py", line 184, in sync_process_output_traits
    nipype_outputs = (process_instance.
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/interfaces/spm/model.py", line 819, in _list_outputs
    outputs["thresholded_map"] = self._gen_thresholded_map_filename()
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/interfaces/spm/model.py", line 658, in _gen_thresholded_map_filename
    _, fname, ext = split_filename(self.inputs.stat_image)
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/utils/filemanip.py", line 96, in split_filename
    pth = op.dirname(fname)
  File "/usr/lib64/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not _Undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/nipype_process.py", line 192, in sync_process_output_traits
    traceback.print_exc()
UnboundLocalError: local variable 'traceback' referenced before assignment
Exception occurred in traits notification handler for object: <capsul.pipeline.pipeline.Pipeline object at 0x7f1e6948a650>, trait: synchronize, old value: 0, new value: 2
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/nipype_process.py", line 184, in sync_process_output_traits
    nipype_outputs = (process_instance.
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/interfaces/spm/model.py", line 819, in _list_outputs
    outputs["thresholded_map"] = self._gen_thresholded_map_filename()
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/interfaces/spm/model.py", line 658, in _gen_thresholded_map_filename
    _, fname, ext = split_filename(self.inputs.stat_image)
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/utils/filemanip.py", line 96, in split_filename
    pth = op.dirname(fname)
  File "/usr/lib64/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not _Undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/home/econdami/.local/lib/python3.7/site-packages/soma_base-4.6.5-py3.7.egg/soma/utils/functiontools.py", line 87, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/pipeline/pipeline_nodes.py", line 235, in _value_callback
    dest_node.set_plug_value(dest_plug_name, value)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/pipeline/pipeline_nodes.py", line 577, in set_plug_value
    self.process.set_parameter(plug_name, value)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/process.py", line 1038, in set_parameter
    setattr(self, name, value)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 545, in __call__
    self.notify_listener(self, object, trait_name, old, new)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 627, in _notify_function_listener
    object, trait_name, old, new, self.handler
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 599, in _dispatch_change_event
    handle_exception(object, trait_name, old, new)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 180, in _handle_exception
    raise excp
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/nipype_process.py", line 192, in sync_process_output_traits
    traceback.print_exc()
UnboundLocalError: local variable 'traceback' referenced before assignment
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/nipype_process.py", line 184, in sync_process_output_traits
    nipype_outputs = (process_instance.
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/interfaces/spm/model.py", line 819, in _list_outputs
    outputs["thresholded_map"] = self._gen_thresholded_map_filename()
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/interfaces/spm/model.py", line 658, in _gen_thresholded_map_filename
    _, fname, ext = split_filename(self.inputs.stat_image)
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/utils/filemanip.py", line 96, in split_filename
    pth = op.dirname(fname)
  File "/usr/lib64/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not _Undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/populse_mia-1.3.0-py3.7.egg/populse_mia/user_interface/pipeline_manager/node_controller.py", line 727, in update_plug_value
    pipeline.nodes[node_name].set_plug_value(plug_name, new_value)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/pipeline/pipeline_nodes.py", line 577, in set_plug_value
    self.process.set_parameter(plug_name, value)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/process.py", line 1038, in set_parameter
    setattr(self, name, value)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 545, in __call__
    self.notify_listener(self, object, trait_name, old, new)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 627, in _notify_function_listener
    object, trait_name, old, new, self.handler
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 599, in _dispatch_change_event
    handle_exception(object, trait_name, old, new)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 180, in _handle_exception
    raise excp
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/home/econdami/.local/lib/python3.7/site-packages/soma_base-4.6.5-py3.7.egg/soma/utils/functiontools.py", line 87, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/pipeline/pipeline_nodes.py", line 235, in _value_callback
    dest_node.set_plug_value(dest_plug_name, value)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/pipeline/pipeline_nodes.py", line 577, in set_plug_value
    self.process.set_parameter(plug_name, value)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/process.py", line 1038, in set_parameter
    setattr(self, name, value)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 545, in __call__
    self.notify_listener(self, object, trait_name, old, new)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 627, in _notify_function_listener
    object, trait_name, old, new, self.handler
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 599, in _dispatch_change_event
    handle_exception(object, trait_name, old, new)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 180, in _handle_exception
    raise excp
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/nipype_process.py", line 192, in sync_process_output_traits
    traceback.print_exc()
UnboundLocalError: local variable 'traceback' referenced before assignment
ok
test_find_process (__main__.TestMIAPipelineManager) ... ok
test_iteration_table (__main__.TestMIAPipelineManager) ... ok
test_process_library (__main__.TestMIAPipelineManager) ... 
 Installing brick_test.Smooth ...

Adding mia_processes.preprocess.spm.Coregister ...

Adding mia_processes.preprocess.spm.NewSegment ...

Adding mia_processes.preprocess.spm.Normalize12 ...

Adding mia_processes.preprocess.spm.Realign ...

Adding mia_processes.preprocess.spm.Smooth ...

Adding mia_processes.studies.Spatial_preprocessing_1 ...

Adding mia_processes.tools.Auto_Filter_List ...

Adding mia_processes.tools.Files_To_List ...

Adding mia_processes.tools.Input_Filter ...

Adding mia_processes.tools.List_Duplicate ...

Adding mia_processes.tools.List_To_File ...

Removing .mia_processes ...

Removing .brick_test ...
ok
test_save_pipeline (__main__.TestMIAPipelineManager) ... /home/econdami/.local/lib/python3.7/site-packages/populse_mia-1.3.0-py3.7.egg/populse_mia/user_interface/pipeline_manager/pipeline_editor.py:1804: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/econdami/.populse_mia/processes/User_processes/test_pipeline.py' mode='w' encoding='UTF-8'>
  writer(pipeline, filename)
ResourceWarning: Enable tracemalloc to get the object allocation traceback

Adding User_processes.Test_pipeline ...
ok
test_undo_redo (__main__.TestMIAPipelineManager) ... ('inputs', 'prefix_smooth') True False False
('inputs', 'prefix_smooth') False False False
('inputs', 'prefix_smooth') False True False

Removing the link:  smooth1._smoothed_files->smooth2.in_files

Removing the link:  smooth1._smoothed_files->smooth2.in_files

Removing the link:  smooth1._smoothed_files->smooth2.in_files
EXCEPTION: 'NoneType' object is not iterable
while syncing nipype parameter out_prefix on Smooth
Exception occurred in traits notification handler for object: <capsul.process.process.NipypeProcess object at 0x7f1e74d25f50>, trait: out_prefix, old value: s, new value: PREFIX
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/nipype_process.py", line 184, in sync_process_output_traits
    nipype_outputs = (process_instance.
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/interfaces/spm/preprocess.py", line 2188, in _list_outputs
    for imgf in ensure_list(self.inputs.in_files):
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/nipype_process.py", line 192, in sync_process_output_traits
    traceback.print_exc()
UnboundLocalError: local variable 'traceback' referenced before assignment
ERROR
test_update_node_name (__main__.TestMIAPipelineManager) ... Node name already in pipeline
ok
test_update_plug_value (__main__.TestMIAPipelineManager) ... EXCEPTION: expected str, bytes or os.PathLike object, not _Undefined
while syncing nipype parameter synchronize on Threshold
Exception occurred in traits notification handler for object: <capsul.process.process.NipypeProcess object at 0x7f1e7bbe0290>, trait: synchronize, old value: 0, new value: 1
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/nipype_process.py", line 184, in sync_process_output_traits
    nipype_outputs = (process_instance.
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/interfaces/spm/model.py", line 819, in _list_outputs
    outputs["thresholded_map"] = self._gen_thresholded_map_filename()
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/interfaces/spm/model.py", line 658, in _gen_thresholded_map_filename
    _, fname, ext = split_filename(self.inputs.stat_image)
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/utils/filemanip.py", line 96, in split_filename
    pth = op.dirname(fname)
  File "/usr/lib64/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not _Undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/nipype_process.py", line 192, in sync_process_output_traits
    traceback.print_exc()
UnboundLocalError: local variable 'traceback' referenced before assignment
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/nipype_process.py", line 184, in sync_process_output_traits
    nipype_outputs = (process_instance.
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/interfaces/spm/model.py", line 819, in _list_outputs
    outputs["thresholded_map"] = self._gen_thresholded_map_filename()
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/interfaces/spm/model.py", line 658, in _gen_thresholded_map_filename
    _, fname, ext = split_filename(self.inputs.stat_image)
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.5.0rc1.post0.dev0+ga70ec9978-py3.7.egg/nipype/utils/filemanip.py", line 96, in split_filename
    pth = op.dirname(fname)
  File "/usr/lib64/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not _Undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/populse_mia-1.3.0-py3.7.egg/populse_mia/user_interface/pipeline_manager/node_controller.py", line 727, in update_plug_value
    pipeline.nodes[node_name].set_plug_value(plug_name, new_value)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/pipeline/pipeline_nodes.py", line 577, in set_plug_value
    self.process.set_parameter(plug_name, value)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/process.py", line 1038, in set_parameter
    setattr(self, name, value)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 545, in __call__
    self.notify_listener(self, object, trait_name, old, new)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 627, in _notify_function_listener
    object, trait_name, old, new, self.handler
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 599, in _dispatch_change_event
    handle_exception(object, trait_name, old, new)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 180, in _handle_exception
    raise excp
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/process/nipype_process.py", line 192, in sync_process_output_traits
    traceback.print_exc()
UnboundLocalError: local variable 'traceback' referenced before assignment
Fatal Python error: Aborted

Current thread 0x00007f1efb1886c0 (most recent call first):
  File "test.py", line 2348 in test_update_plug_value
  File "/usr/lib64/python3.7/unittest/case.py", line 628 in run
  File "/usr/lib64/python3.7/unittest/case.py", line 676 in __call__
  File "/usr/lib64/python3.7/unittest/suite.py", line 122 in run
  File "/usr/lib64/python3.7/unittest/suite.py", line 84 in __call__
  File "/usr/lib64/python3.7/unittest/suite.py", line 122 in run
  File "/usr/lib64/python3.7/unittest/suite.py", line 84 in __call__
  File "/usr/lib64/python3.7/unittest/runner.py", line 176 in run
  File "/usr/lib64/python3.7/unittest/main.py", line 271 in runTests
  File "/usr/lib64/python3.7/unittest/main.py", line 101 in __init__
  File "test.py", line 2675 in <module>
Aborted (core dumped)


```

**Comment by denisri** [comment]
3ec7781b51fc99b03cf682b014ada1e6b57d7f23 seems to have fixed the problem.

**Comment by servoz** [comment]
Oh yeah ! It's fixed, thank you very much @denisri .
There are a few additional warnings or exceptions that are caught, so it doesn't crash the tests. I don't know if it would be worth looking to? The problem is that we have so much to do that when it works it's hard to take the time to look at ... anyhow the inital issue is fixed so i close it

**Comment by denisri** [comment]
Some nipype traits don't allow Undefined values, but are initialized with Undefined values or defaults (or something like this), so it causes some errors in value change handlers. It's difficult to investigate since we don't have callers and what/why in traits change in tracebacks. But I agree it would be useful...

**Comment by servoz** [comment]
OK for nipype but there are also:
```
- /home/econdami/.local/lib/python3.7/site-packages/populse_mia-1.3.0-py3.7.egg/populse_mia/user_interface/pipeline_manager/pipeline_editor.py:1804: ResourceWarning: unclosed file <_io.TextIOWrapper name='../../../../../home/econdami/.populse_mia/processes/User_processes/test_pipeline.py' mode='w' encoding='UTF-8'>
  writer(pipeline, filename)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
in test_zz_check_modifications (__main__.TestMIAPipelineManager)

and
```
-Exception ignored in: <function PipelineDevelopperView.__del__ at 0x7f2cf50c77a0>
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 2545, in __del__
    self.release_pipeline()
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 2622, in release_pipeline
    self.scene = PipelineScene(self)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 1434, in __init__
    super(PipelineScene, self).__init__(parent)
RuntimeError: wrapped C/C++ object of type PipelineEditor has been deleted
Exception ignored in: <function PipelineScene.__del__ at 0x7f2cf511b560>
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 1458, in __del__
    if hasattr(self, 'pos'):
RuntimeError: super-class __init__() of type PipelineScene was never called
Exception ignored in: <function PipelineDevelopperView.__del__ at 0x7f2cf50c77a0>
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 2545, in __del__
    self.release_pipeline()
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 2622, in release_pipeline
    self.scene = PipelineScene(self)
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 1434, in __init__
    super(PipelineScene, self).__init__(parent)
RuntimeError: wrapped C/C++ object of type PipelineEditor has been deleted
Exception ignored in: <function PipelineScene.__del__ at 0x7f2cf511b560>
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/capsul-2.2.1-py3.7.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 1458, in __del__
    if hasattr(self, 'pos'):
RuntimeError: super-class __init__() of type PipelineScene was never called
test_delete_processes (__main__.TestMIAPipelineManager)
Deletes a process and makes the undo/redo action ... /home/econdami/.local/lib/python3.7/site-packages/soma_base-4.6.5-py3.7.egg/soma/utils/functiontools.py:135: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  return inspect.getargspec(callable)
```
in test_close_tab (__main__.TestMIAPipelineManager)

I think i have already seen the last one when closing mia, not each time.

**Comment by denisri** [comment]
yes I have seen that. There are some cyclic references in PipelineDevelopperView objects, some of them are due to callbacks / slots (most callbacks are instance methods, thus contain a reference to the object, and prevent their deletion), whereas Qt (C++) actually destroys objects when a parent widget is deleted. Hence the message `wrapped C/C++ object of type <something> has been deleted`. It's not easy to fix, perhaps callbacks should be explicitly removed when the widgets are closed.
