### ISSUE TITLE
Easy local configuration of Nipype is broken

### ISSUE THREAD

**Issue by sapetnioc** [populse/capsul#166]
The QualiCATI project is using capsul engine to configure Nipype for SPM standalone. The code it uses in now broken. We must provide an updated way to do the following :
```import os.path as osp

from capsul.in_context.nipype import configure_all as configure_nipype
from capsul.api import capsul_engine

config = {'spm' : {'use':True,
                    'directory': osp.expanduser('/cati/spm12-standalone'),
                    'standalone':True}}
ce = capsul_engine(config=config)
ce.__enter__()
configure_nipype()
```

**Comment by sapetnioc** [comment]
I am trying the following code to configure SPM but there is an error due to the link with StudyConfig. Is it possible to make this link optional when we are sure there is no old code in the project ?

The following code :

```ce = capsul_engine(require=['spm'])
with ce.settings as settings:
    settings.new_config('spm', 'global',
                        {'directory': '/cati/spm12-standalone',
                         'standalone': True})
```
lead to the following error :
```
Traceback (most recent call last):
  File "/casa/home/test.py", line 10, in <module>
    'standalone': True})
  File "/casa/src/capsul/capsul/engine/settings.py", line 279, in new_config
    config.notify()
  File "/casa/src/capsul/capsul/engine/settings.py", line 360, in notify
    notifier(name, value)
  File "/casa/src/capsul/capsul/study_config/config_modules/spm_config.py", line 90, in sync_from_engine
    key=lambda x: (-int(x.version) if x.version != ''
  File "/casa/src/capsul/capsul/study_config/config_modules/spm_config.py", line 90, in <lambda>
    key=lambda x: (-int(x.version) if x.version != ''
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by sapetnioc** [comment]
I think the code for my example should be something like that :
```from capsul.api import capsul_engine, activate_configuration

ce = capsul_engine()
with ce.settings as settings:
    settings.new_config('spm', 'global',
                        {'directory': '/cati/spm12-standalone',
                         'standalone': True,
                         'version': 12})

conf = ce.settings.select_configurations('global',
                                         uses={'spm': 'any',
                                               'nipype': 'any'})
activate_configuration(conf)
```

If I am not wrong, we have to check that SPM standalone in Nipype is properly configured with this code.

**Comment by sapetnioc** [comment]
Well, there is no more guessing of SPM version. So, to be complete, the equivalent code is the following :
```import os.path as osp
from capsul.api import capsul_engine, activate_configuration


spm_directory = '/cati/spm12-standalone'
if osp.isdir(osp.join(spm_directory, 'spm12_mcr')):
    spm_version = '12'
elif osp.isdir(osp.join(spm_directory, 'spm8_mcr')):
    spm_version = '8'
else:
    raise ValueError('Unknown SPM version in %s' % spm_directory)

ce = capsul_engine()
with ce.settings as settings:
    settings.new_config('spm', 'global',
                        {'directory': spm_directory,
                         'standalone': True,
                         'version': spm_version})

conf = ce.settings.select_configurations('global',
                                         uses={'spm': 'any',
                                               'nipype': 'any'})
activate_configuration(conf)
```

**Comment by sapetnioc** [comment]
I have been told that the previous code is working for SPM+Nipype.
