### ISSUE TITLE
[Initialisation step] Mia does not support now a pipeline launching without input parameters error.

### ISSUE THREAD

**Issue by servoz** [populse/capsul#199]
The minimum steps to reproduce :

- Open Mia
- Open a project
- In the pipeline manager, drag and drop the SPM Smooth brick from mia_processes into the editor
- Click on the "Run pipeline" button (this is an error as we have not yet defined the input parameters, but errors should be handled in Mia).
- We observe in the status bar: Pipeline "NoName" was not initialised successfully and in the stdout:
```
 Pipeline initialising ...
Completion / workflow...
. main (mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth) MIA node ...
During the <mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth object at 0x7f8b95c12bf8> process initialisation, some possible problems were detected:
- inheritance_dict attribute was not found ...
- outputs attribute was not found ...
Workflow done.
Error during initialisation of the "NoName" pipeline ...!
Traceback:
  File "/casa/home/Git_projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1301, in initialize
    self.test_init = self.init_pipeline()
  File "/casa/home/Git_projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1385, in init_pipeline
    missing_inputs = self.get_missing_mandatory_parameters()
  File "/casa/home/Git_projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1278, in get_missing_mandatory_parameters
    if node is self.get_current_pipeline().pipeline_node:
AttributeError: 'PipelineManagerTab' object has no attribute 'get_current_pipeline'

```
- If we now want to get things right it seems impossible:
  - Right click in the brick and choose "Export all unconnected records" (all nodes turn blue)
  - Select a in_files parameter using the Filter button
  - Click on the "Run pipeline" button
  - A pop-up window open with the message "The pipeline could not be initailsed properly"
  - We see in stdout:

```
 ERROR:traits:Exception occurred in traits notification handler for object: <mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth object at 0x7f8b95c12bf8>, trait: in_files, old value: <undefined>, new value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/rocmi_120618test1-IRMFonct_+perfusion-2018-06-12060428-05-T13DSENSE-T1TFE-000424_000.nii']
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists
ERROR:traits:Exception occurred in traits notification handler for object: <capsul.pipeline.pipeline.Pipeline object at 0x7f8bb210e360>, trait: in_files, old value: <undefined>, new value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/rocmi_120618test1-IRMFonct_+perfusion-2018-06-12060428-05-T13DSENSE-T1TFE-000424_000.nii']
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 735, in set_plug_value
    self.process.set_parameter(plug_name, value, protected)
  File "/casa/host/src/capsul/master/capsul/process/process.py", line 1043, in set_parameter
    setattr(self, name, value)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 478, in __call__
    self.notify_listener(self, object, trait_name, old, new)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 561, in _notify_function_listener
    object, trait_name, old, new, self.handler
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 532, in _dispatch_change_event
    handle_exception(object, trait_name, old, new)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 149, in _handle_exception
    raise excp
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists
weakly-referenced object no longer exists
ERROR:traits:Exception occurred in traits notification handler for object: <mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth object at 0x7f8b95c12bf8>, trait: in_files, old value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/rocmi_120618test1-IRMFonct_+perfusion-2018-06-12060428-05-T13DSENSE-T1TFE-000424_000.nii'], new value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/alej170316_test24042018-IRMFonct_+perfusion-2016-03-17083444-00-T13DSENSE-T1TFE-000425_000.nii']
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline
 /pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists
ERROR:traits:Exception occurred in traits notification handler for object: <capsul.pipeline.pipeline.Pipeline object at 0x7f8bb210e360>, trait: in_files, old value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/rocmi_120618test1-IRMFonct_+perfusion-2018-06-12060428-05-T13DSENSE-T1TFE-000424_000.nii'], new value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/alej170316_test24042018-IRMFonct_+perfusion-2016-03-17083444-00-T13DSENSE-T1TFE-000425_000.nii']
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 735, in set_plug_value
    self.process.set_parameter(plug_name, value, protected)
  File "/casa/host/src/capsul/master/capsul/process/process.py", line 1043, in set_parameter
    setattr(self, name, value)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 478, in __call__
    self.notify_listener(self, object, trait_name, old, new)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 561, in _notify_function_listener
    object, trait_name, old, new, self.handler
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 532, in _dispatch_change_event
    handle_exception(object, trait_name, old, new)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 149, in _handle_exception
    raise excp
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists
weakly-referenced object no longer exists
ERROR:traits:Exception occurred in traits notification handler for object: <mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth object at 0x7f8b95c12bf8>, trait: in_files, old value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/alej170316_test24042018-IRMFonct_+perfusion-2016-03-17083444-00-T13DSENSE-T1TFE-000425_000.nii'], new value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/rocmi_120618test1-IRMFonct_+perfusion-2018-06-12060428-05-T13DSENSE-T1TFE-000424_000.nii']
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists
ERROR:traits:Exception occurred in traits notification handler for object: <capsul.pipeline.pipeline.Pipeline object at 0x7f8bb210e360>, trait: in_files, old value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/alej170316_test24042018-IRMFonct_+perfusion-2016-03-17083444-00-T13DSENSE-T1TFE-000425_000.nii'], new value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/rocmi_120618test1-IRMFonct_+perfusion-2018-06-12060428-05-T13DSENSE-T1TFE-000424_000.nii']
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 735, in set_plug_value
    self.process.set_parameter(plug_name, value, protected)
  File "/casa/host/src/capsul/master/capsul/process/process.py", line 1043, in set_parameter
    setattr(self, name, value)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 478, in __call__
    self.notify_listener(self, object, trait_name, old, new)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 561, in _notify_function_listener
    object, trait_name, old, new, self.handler
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 532, in _dispatch_change_event
    handle_exception(object, trait_name, old, new)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 149, in _handle_exception
    raise excp
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists
weakly-referenced object no longer exists
- Pipeline initialising ...

Completion / workflow...
ERROR:traits:Exception occurred in traits notification handler for object: <mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth object at 0x7f8b95c12bf8>, trait: spm_script_file, old value: /data/IRM/projects_mia/rel2_test/scripts/pyscript_smooth_47858d10-988a-40cd-8ca0-67057f9ddd9a.m, new value: /data/IRM/projects_mia/rel2_test/scripts/pyscript_smooth_a7d60f4e-8ed2-40eb-906f-a29131fe221d.m
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists

Workflow done.

init time: 0.05649566650390625

```

**Comment by servoz** [comment]
I'm trying to catch up on what's been done, while I'm on other business...

Yes @denisri , your fix works perfectly and I don't see the issues raised in this ticket anymore! Thanks !

However, two things remain:
- 1 Colors: @Denis, do you remember what the blue color code for the gnodes corresponds to. In fact by following the "minimum steps to reproduce" in the first message of this ticket, after having done `Right click in the brick and choose "Export all unconnected records" (all nodes turn blue)`, we observe these colors for the gnodes:
![Screenshot from 2022-01-27 11-15-19](https://user-images.githubusercontent.com/37933899/151346418-bc188492-d8c5-48bd-8ff4-517ceb66712d.png)
I have already observed this without knowing exactly what this change of color corresponds to? I have just looked (diagonally) at the capsul.qt_gui.widgets.pipeline_developer_view module and I did not find an obvious answer to my question (maybe it is necessary to read it more carefully than diagonally!).

- 2 name issue: If we run the Smooth brick of mia_processes (or directly form nipype), without making the mistake of forgetting to define the input parameter, the name of the brick/process is correctly used in the stdout and in the database:
![Screenshot from 2022-01-27 11-39-30](https://user-images.githubusercontent.com/37933899/151346921-dba4fa85-6f7f-4960-a101-41a3d0888592.png)
![Screenshot from 2022-01-27 11-38-37](https://user-images.githubusercontent.com/37933899/151346969-4be9d182-5497-46d4-831f-9a32444f452c.png)
On the other hand, if we follow the procedure of the first message in this ticket we observe the name `main` instead of `smooth_1`.
![Screenshot from 2022-01-27 11-52-04](https://user-images.githubusercontent.com/37933899/151347098-4db19c95-2164-4c4f-84c7-03953b02ceff.png)
![Screenshot from 2022-01-27 11-50-51](https://user-images.githubusercontent.com/37933899/151347108-cf23f868-1ffe-424d-9c7a-de0aa4de9574.png)
Perhaps another ticket should be opened for this particular issue?

**Comment by servoz** [comment]
In order to update or close if necessary the tickets, I just retested the issues raised by this ticket.

The 2 initial problems described in this ticket are now effectively fixed.

On the other hand, a new problem has appeared. To summarise, if we follow the procedure described in the first post, it seems that the pipeline loses its name. So in the DataBrowser we see for the Bricks tag of the image after smooth the name `main` instead of `Smooth`, and in the status bar we have the message `Pipeline "NoName" has been correctly run` instead of `Pipeline "Smooth" has been correctly run`.

For the blue color I will search by myself, you are never as well served as when you serve yourself.

I don't know if this new issue is to be fixed in capsul or in populse_mia, but in order not to leave old unresolved tickets lying around, I'll close this one and open a new one in populse_mia
