### ISSUE TITLE
Tests fail with Redis 4.5.0

### ISSUE THREAD

**Issue by sapetnioc** [populse/capsul#261]
Since Redis 4.5.0 is on PyPi, many tests are failing with the following error:
```
======================================================================
ERROR: test_direct_run (capsul.pipeline.test.test_proc_with_outputs.TestPipelineContainingProcessWithOutputs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/capsul/capsul/capsul/pipeline/test/test_proc_with_outputs.py", line 254, in test_direct_run
    with self.capsul.engine() as ce:
  File "/home/runner/work/capsul/capsul/capsul/engine/__init__.py", line 77, in __enter__
    self.database.__enter__()
  File "/home/runner/work/capsul/capsul/capsul/database/__init__.py", line 102, in __enter__
    self._enter()
  File "/home/runner/work/capsul/capsul/capsul/database/redis.py", line 83, in _enter
    self.redis.delete("capsul:shutting_down")
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/redis/commands/core.py", line 1673, in delete
    return self.execute_command("DEL", *names)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/redis/client.py", line 1258, in execute_command
    return conn.retry.call_with_retry(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/redis/client.py", line 1259, in <lambda>
    lambda: self._send_command_parse_response(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/redis/client.py", line 1234, in _send_command_parse_response
    conn.send_command(*args)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/redis/connection.py", line 916, in send_command
    self._command_packer.pack(*args),
AttributeError: 'UnixDomainSocketConnection' object has no attribute '_command_packer'
```

**Comment by sapetnioc** [comment]
This issue was fixed in 4.5.1.
However releases 4.5.2 and 4.5.3 have another bug that prevent tests for running.
I will keep this issue open until it is possible to use `pip install -U redis` and have the tests running.
